import "./globals.css";
import { Inter } from "next/font/google";
import Nav from "./components/Nav";
import localFont from "next/font/local";

const satoshi = localFont({
  src: [
    {
      path: "../public/fonts/Satoshi-Regular.woff2",
      weight: "400",
    },
    {
      path: "../public/fonts/Satoshi-Bold.woff2",
      weight: "700",
    },
    {
      path: "../public/fonts/Satoshi-Medium.woff2",
      weight: "500",
    },
  ],
  variable: "--font-satoshi",
});
const cabinet = localFont({
  src: [
    {
      path: "../public/fonts/CabinetGrotesk-Variable.ttf",
    },
  ],
  variable: "--font-cabinet",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${satoshi.variable} ${cabinet.variable} font-sans`}
    >
      <body className="bg-[url('/test.webp')]">{children}</body>
    </html>
  );
}
